apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-stress-test
  labels:
    app: gc-stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gc-stress-test
  template:
    metadata:
      labels:
        app: gc-stress-test
    spec:
      containers:
      - name: gc-stress-test
        image: itestmycode/gc-stress-test:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
