apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-stress-test
  labels:
    app: gc-stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gc-stress-test
  template:
    metadata:
      labels:
        app: gc-stress-test
    spec:
      containers:
      - name: gc-stress-test
        image: itestmycode/gc-stress-test:0.0.1
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseParallelGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -Xlog:gc*:stdout:time,tags -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/heapdump.hprof"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
